services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: budget_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6675
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

  django:
    build:
      context: ./budget_tracker  # Points to the root directory
      dockerfile: Dockerfile.backend  # Specifies the backend Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata initial_data.json &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./budget_tracker:/app
    depends_on:
      - postgres
    environment:
      ENVIRONMENT: docker  # Specify Docker environment
      DB_NAME: budget_tracker_db
      DB_USER: postgres
      DB_PASSWORD: 6675
      DB_HOST: postgres

  react:
    build:
      context: ./budget_tracker/my_budget_tracker_app  # Points to React inside budget_tracker
      dockerfile: Dockerfile.frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./budget_tracker/my_budget_tracker_app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for live reload on some systems
      REACT_APP_API_BASE_URL=http://localhost:8000/api/

volumes:
  postgres_data:
