# Generated by Django 5.0.2 on 2024-03-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_income_income_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomeCategory',
            new_name='IncomesCategory',
        ),
    ]
