# Generated by Django 5.0.2 on 2024-03-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_incomecategory_incomescategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomesCategory',
            new_name='ExpenseCategory',
        ),
        migrations.RenameModel(
            old_name='ExpensesCategory',
            new_name='IncomeCategory',
        ),
    ]
