# Generated by Django 5.0.2 on 2024-03-11 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_expense_is_recurring_income_is_recurring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpenseChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField()),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amount_changes', to='tracker.expense')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringIncomeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField()),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='tracker.income')),
            ],
        ),
        migrations.DeleteModel(
            name='RecurringAmountChange',
        ),
    ]
