# Generated by Django 5.0.2 on 2024-03-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_creditcard_close_card_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='interest_rate',
            new_name='Surcharge',
        ),
    ]
