# Generated by Django 5.0.2 on 2024-03-16 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_rename_interest_rate_expense_surcharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Surcharge',
            new_name='surcharge',
        ),
        migrations.AlterField(
            model_name='expense',
            name='credit_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tracker.creditcard'),
        ),
    ]
