# Generated by Django 5.0.3 on 2024-06-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_rename_surcharge_expense_surcharge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='income_category',
            new_name='category',
        ),
    ]
