# Generated by Django 5.0.3 on 2024-06-14 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_rename_expense_category_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='pay_with_credit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tracker.creditcard'),
        ),
    ]
