# Generated by Django 5.0.3 on 2024-06-16 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_expense_pay_with_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='tracker.creditcard'),
        ),
    ]
