# Generated by Django 5.0.3 on 2024-06-16 03:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_alter_expense_credit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='close_card_day',
            field=models.IntegerField(default=21, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='last_four_digits',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Last four digits must be exactly 4 digits', regex='^\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='payment_day',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
