# Generated by Django 5.0.3 on 2024-08-27 23:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_delete_recurringchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseRecurringChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('effective_date', models.DateField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='tracker.expense')),
            ],
            options={
                'ordering': ['effective_date'],
                'unique_together': {('expense', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='IncomeRecurringChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('effective_date', models.DateField()),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='tracker.income')),
            ],
            options={
                'ordering': ['effective_date'],
                'unique_together': {('income', 'effective_date')},
            },
        ),
    ]
